name: Deploy backend

on:
  workflow_dispatch:
  push:
    paths:
      - 'nest-backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: NPM Ci
        run: |
          cd nest-backend/
          npm ci -f

      - name: Build
        run: |
          cd nest-backend/
          npm run prebuild && npm run build --if-present

      - name: Copy package.json to dist
        run: |
          cd nest-backend/
          cp package.json dist/

#      - name: Test
#        run: |
#          cd nest-backend/
#          npm run test

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync -avuz --delete --exclude=".*" nest-backend/dist ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/lib/pterodactyl/volumes/cb4da89f-ac2e-4660-a274-981d8c9838b6/

  stop-server:
    needs: deploy
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Stop
        run: |
          curl --location --request POST 'https://nuerk-solutions.de/api/client/servers/cb4da89f/power' \
          --header 'Accept: application/json' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer liImK09QTJU7KJyP9jqMF6vyDiSsaTDzt1d6eixd5OUy18MS' \
          --data-raw '{
            "signal": "kill"
          }'

  start-server:
    needs: stop-server
    runs-on: ubuntu-latest
    steps:
      - name: Start
        run: |
          curl --location --request POST 'https://nuerk-solutions.de/api/client/servers/cb4da89f/power' \
          --header 'Accept: application/json' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer liImK09QTJU7KJyP9jqMF6vyDiSsaTDzt1d6eixd5OUy18MS' \
          --data-raw '{
            "signal": "start"
          }'
